// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaxD7m66zwmOVWjQ-1kQZbz0Ez0IxF60',
    appId: '1:208267977837:web:0f836839278c8a52054b64',
    messagingSenderId: '208267977837',
    projectId: 'new-capstone-480be',
    authDomain: 'new-capstone-480be.firebaseapp.com',
    storageBucket: 'new-capstone-480be.appspot.com',
    measurementId: 'G-T021J0QW7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrb_0nmQwzeksTfpD8qvRphIxcIOt8taI',
    appId: '1:208267977837:android:eba6b87d65e99f10054b64',
    messagingSenderId: '208267977837',
    projectId: 'new-capstone-480be',
    storageBucket: 'new-capstone-480be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCriJbP8XwhA3KCMUuSuIsEvi4ACuEEqHM',
    appId: '1:208267977837:ios:5c3261a9aca0e063054b64',
    messagingSenderId: '208267977837',
    projectId: 'new-capstone-480be',
    storageBucket: 'new-capstone-480be.appspot.com',
    iosClientId: '208267977837-ah8nuqbd7gdpq7e8mq1c48fnps8sop25.apps.googleusercontent.com',
    iosBundleId: 'com.example.newcapstone',
  );
}
